name       : gst-rtsp-server
version    : 1.18.2
release    : 6
source     :
    - https://gitlab.freedesktop.org/gstreamer/gst-rtsp-server/-/archive/1.18.2/gst-rtsp-server-1.18.2.tar.gz : 9ba3be579d618491176c2c3bd7d9c7e5f64d1a9400fd2463f1224b1576e84fa8
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.gstreamer
summary    : GStreamer RTSP server library
description: |
    GStreamer's RTSP server (gst-rtsp-server) is a featureful and easy-to-use library that allows applications to implement a complete RTSP server with just a couple of lines of code.
builddeps  :
    - pkgconfig(gstreamer-plugins-bad-1.0)
setup      : |
    %meson_configure \
        -Dpackage-name="GStreamer ${version} Solus" \
        -Dpackage-origin="https://getsol.us"
build      : |
    %ninja_build
install    : |
    %ninja_install
