name       : gst-rtsp-server
version    : 1.14.4
release    : 3
source     :
    - https://gstreamer.freedesktop.org/src/gst-rtsp-server/gst-rtsp-server-1.14.4.tar.xz : 3d0ece2afdcd601c175ece24e32a30bc19247b454f4eafd3deeec2533c6884f1
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.gstreamer
summary    : GStreamer RTSP server library
description: |
    GStreamer's RTSP server (gst-rtsp-server) is a featureful and easy-to-use library that allows applications to implement a complete RTSP server with just a couple of lines of code.
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
setup      : |
    %meson_configure \
        -Dwith-package-name="GStreamer ${version} Solus" \
        -Dwith-package-origin="https://getsol.us" \
        -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
