name       : gst-rtsp-server
version    : 1.14.2
release    : 1
source     :
    - https://gstreamer.freedesktop.org/src/gst-rtsp-server/gst-rtsp-server-1.14.2.tar.xz : f7387755cf6ac5f334d4610f1f5aa7da4ff396a487dd5b789bb707f160222c98
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.gstreamer
summary    : GStreamer RTSP server library
description: |
    GStreamer's RTSP server (gst-rtsp-server) is a featureful and easy-to-use library that allows applications to implement a complete RTSP server with just a couple of lines of code.
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
setup      : |
    %meson_configure \
        -Dwith-package-name="GStreamer ${version} Solus" \
        -Dwith-package-origin=https://solus-project.com \
        -Dtests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
